### ISSUE TITLE
Resource Purchase Validation Failed

### ISSUE THREAD

**Issue by rpdebeer** [arnstran/CHKP-VMSS_Collapsed_Blueprint#1]
1 error occurred:
        * azurerm_virtual_machine_scale_set.vmss: 1 error occurred:
        * azurerm_virtual_machine_scale_set.vmss: compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ResourcePurchaseValidationFailed" Message="User failed validation to purchase resources. Error message: 'Offer with PublisherId: checkpoint and OfferId: check-point-cg-r8020-blink-v2 not found. If this offer has been created recently, please allow up to 30 minutes for this offer to be available for Purchase. If error persists, contact support.'"

**Comment by arnstran** [comment]
Was due to issues in Azure. Fixed now
